### ISSUE TITLE
Some more orgs for ya

### ISSUE THREAD

**Issue by cjdd3b** [silva-shih/open-journalism#14]
Hey guys — Thanks for doing this. I was rounding up a similar list for a separate project, and I ran into 20 or so more orgs that you haven't listed yet. Hope this helps!

[Louisville Courier-Journal](https://github.com/courierjournal)
[Daily Herald (Arlington Heights, IL)](https://github.com/dailyherald)
[Democrat and Chronicle (Rochester, N.Y.)](https://github.com/dandc)
[New Castle News Journal](https://github.com/delawaredata)
[Hearst](https://github.com/HearstCorp)
[KQED-San Francisco](https://github.com/kqed)
[La Opinion](https://github.com/laopinion/)
[White Plains Journal News](https://github.com/lohud)
[New York Post](https://github.com/newyorkpost)
[Journal Star (Peoria, IL)](https://github.com/pjstar)
[Charleston Post and Courier](https://github.com/postandcourier)
[San Antonio Express-News](https://github.com/sa-express-news)
[Sacramento Bee](https://github.com/sacbee)
[KPCC-Los Angeles](https://github.com/SCPR)
[The Salt Lake Tribune](https://github.com/sltrib)
[South Florida Sun Sentinel](https://github.com/SunSentinel)
[Advocate (Baton Rouge)](https://github.com/theadvocate)
[Buffalo News](https://github.com/thebuffalonews)
[Portland Oregonian](https://github.com/TheOregonian)
[The Virginian-Pilot](https://github.com/virginianpilot)
[WBEZ-Chicago](https://github.com/wbez)
[WGBH-Boston](https://github.com/WGBH)

**Comment by kleinmatic** [comment]
Whoah, thanks, Chase. Gonna add these.

**Comment by kleinmatic** [comment]
Added.
