### ISSUE TITLE
Moar media org repos

### ISSUE THREAD

**Issue by donohoe** [silva-shih/open-journalism#15]
- Houston Chronicle (nothing public yet)
  - https://github.com/houstonchronicle. 
- Conde Nast
  - https://github.com/CondeNast
- The New Yorker / Conde Nast
  - https://github.com/newyorker 
- Hearst
  - https://github.com/Hearst-DD 
  - https://github.com/Hearst-Hatchery

**Comment by kleinmatic** [comment]
Thanks! These are in.
