### ISSUE TITLE
Some french newspapper ?

### ISSUE THREAD

**Issue by herdir** [silva-shih/open-journalism#18]
Hi i'm sending you here some french newspaper who are working on GitHub 
Not sure if i`m  not off-topic also ...

https://github.com/canalplus
https://github.com/francetv
https://github.com/liberation

**Comment by kleinmatic** [comment]
Thank you! I've added Libération but the other two -- are they just for the newsroom or are they for the whole broadcast company?

**Comment by herdir** [comment]
yep sorry my bad its for the broadcast
