### ISSUE TITLE
Two I don't know...

### ISSUE THREAD

**Issue by kleinmatic** [silva-shih/open-journalism#2]
Hi Silva,

Can you please tell me more about Initium Lab and The Reporter? Are they independent groups or news organizations of their own? What kind of work do they do, etc.? I'm very sorry to be ignorant about them.

Cheers
Scott

**Comment by silva-shih** [comment]
Hi Scott, 

No worries. They are both regional media. [Initium](https://theinitium.com/) is a digital news publication based in Hong Kong, cover China, Hong Kong and Taiwan. [The Reporter](https://www.twreporter.org/) is a non-profit news org based in Taiwan, follow the Propublica's business model, emphasize on investigative reporting.  Both of them launched their sites at the end of last year and regarded as very influential news outlets, in terms of knowing how to use digital tools and focusing on in-depth coverages, in a very short time. 

If you're interested in, you can follow Initium's lab blog (in English):[https://initiumlab.com/]( https://initiumlab.com/) or The Reporter's medium account [@twreporter](https://medium.com/twreporter/) (only in Chinese, but google translate tool might work) to learn more about their stories. 

Hope it explains well! 

Silva

**Comment by kleinmatic** [comment]
Perfect, thanks! I'll get them into the @newsnerdrepos ifttt recipe.

**Comment by kleinmatic** [comment]
OK, they're added!
